apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine-container
spec:
  selector:
    matchLabels:
      app: alpine
  replicas: 1
  template: 
    metadata:
      labels: 
        app: alpine
    spec:
      containers:
        - name: alpine-app
          image: motarski/test-alpine:latest
          command: ["/bin/sh"]
          args: ["-c", "while true; do echo hello; sleep 10;done"]
          
