apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name:  alpine-container
  namespace: argocd
spec: 
  project: default

  source: 
    repoURL: https://github.com/motarski/argocd-alpine-test.git
    path: staging
    targetRevision: HEAD

  destination:
    server: https://kubernetes.default.svc
    namespace: alpine

  syncPolicy:
    syncOptions: 
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
